project:
  type: website
  output-dir: docs  # Obligatorio por la rúbrica para subirlo a GitHub Pages

website:
  title: "Minería de Datos - Proyecto Final"
  navbar:
    background: primary
    left:
      - href: notebooks/01_EDA.ipynb
        text: "1. Análisis Exploratorio (EDA)"

format:
  html:
    theme: cosmo
    toc: true          # Genera una tabla de contenidos automática a la derecha
    code-fold: true    # Permite a la profesora ocultar/mostrar tu código de Python
    code-tools: true   # Agrega herramientas para ver el código fuente