project:
  type: website
  output-dir: docs

website:
  title: "Minería de Datos - Ciencias UNAM"
  navbar:
    background: primary
    left:
      - text: "Inicio"
        href: index.qmd
      - text: "1. EDA"
        href: notebooks/EDA.ipynb
      - text: "2. Modelo Supervisado"
        href: notebooks/Modelo.ipynb
      - text: "3. Clustering"
        href: notebooks/Clustering.ipynb

format:
  html:
    theme: cosmo
    toc: true
    toc-title: "Contenido de la Sección"
    code-fold: true
    code-summary: "Mostrar Código Python"
    lang: es